stages:
  - publish_npm
  - publish_brew

publish_npm:
  stage: publish_npm
  image:
    name: node:12.18.1
  when: manual
  before_script:
    - apt-get update && apt-get install -y p7zip-full
    - npm install -g @oclif/dev-cli
    - npm install -g typescript
    - npm install -g aws-sdk
    - npm version
    - oclif-dev -v
  script:
    - npm install
    - oclif-dev pack
    - oclif-dev publish
    - npm config set '//registry.npmjs.org/::_authToken' "${NPM_TOKEN}"
    - npm publish
  only:
    - master
    - develop
  tags:
    - eks-dev-infra

publish_brew:
  stage: publish_brew
  image:
    name: node:12.18.1
  when: manual
  script:
    - npm version
  only:
    - master
    - develop
  tags:
    - eks-dev-infra
