enum DeploymentStatusEnum {
  DEPLOYMENT_INITIALIZED = 'DEPLOYMENT_INITIALIZED',
  DEPLOYMENT_IN_PROGRESS = 'DEPLOYMENT_IN_PROGRESS',
  DEPLOYED = 'DEPLOYED',
  DEPLOYMENT_FAILED = 'DEPLOYMENT_FAILED',
}

export default DeploymentStatusEnum;
