enum ServiceStateEnum {
  GIT_REPOSITORY_IN_PROGRESS = 'GIT_REPOSITORY_IN_PROGRESS',
  GIT_REPOSITORY_CREATED = 'GIT_REPOSITORY_CREATED',
  GIT_REPOSITORY_FAILURE = 'GIT_REPOSITORY_FAILURE',
  NEW_CONTAINER_IMAGE_AVAILABLE = 'NEW_CONTAINER_IMAGE_AVAILABLE',
}

export default ServiceStateEnum;
